---
subsystemInstant:
  owningOrganizationName: "ACT Health"
  solutionName: "AETHER"
  solutionGroup: "au.gov.act.health.aether"
  solutionDescription: "Message Ingestion, Transformation and Forwarding (MITaF) - HIPS"
  subsystemName: "aether-mitaf-hips"
  subsystemVersion: "1.5.0"
  externalisedServiceName: "aether-mitaf-hips"
  externalisedServiceDNSName: "mitaf-hips.sitea.aether.local"
  externalisedServiceEndpointName: null
  clusterServiceName: "aether-mitaf-hips"
  clusterServiceDNSName: "10.123.123.10"
  processingPlantDNSName: "aether-mitaf-hips"
  processingPlantVersion: "1.5.0-SNAPSHOT"
  site: "Site-A"
  participantName: "MITaF.HIPS"
deploymentMode:
  deploymentConfig: "/var/lib/configfiles/subsystem/aether-mitaf-hips/systemconfig-microk8s-site-a.yaml"
  petasosIPCStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-ipc-microk8s.xml"
  petasosTopologyStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-topology-microk8s.xml"
  petasosMetricsStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-metrics-microk8s.xml"
  petasosInterceptionStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-interception-microk8s.xml"
  petasosSubscriptionStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-subscriptions-microk8s.xml"
  petasosTaskingStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-tasking-microk8s.xml"
  petasosAuditStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-audit-microk8s.xml"
  multiuseInfinispanStackConfigFile: "/var/lib/configfiles/network/jgroups/multi-zone-infinispan-microk8s.xml"
  kubernetes: true
  processingPlantReplicationCount: 1
  concurrent: false
  usingInternalEncryption: true
deploymentSites:
  siteCount: 1
  site1Name: "Site-A"
  site2Name: null
  site3Name: null
deploymentZone:
  securityZoneName: "PrivateNetwork"
  nameSpace: "site-a"
kubeReadinessProbe:
  serverPort: 9990
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/health"
  server: true
  encrypted: false
  startupDelay: 60
kubeLivelinessProbe:
  serverPort: 9990
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/health"
  server: true
  encrypted: false
  startupDelay: 60
prometheusPort:
  serverPort: 0
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/"
  server: true
  encrypted: false
jolokiaPort:
  serverPort: 8080
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/"
  server: true
  encrypted: false
subsystemImageProperties:
  repository: "localhost:32000/"
  imageName: "aether-mitaf-hips"
  imageVersion: "1.5.0-SNAPSHOT"
  pullPolicy: "Always"
defaultServicePortLowerBound: 16270
loadBalancer:
  type: "LoadBalancer"
  ipAddress: "10.123.123.10"
volumeMounts:
  mappedLocalStorage:
    - volumeName: "certificates"
      volumeMountPath: "/var/lib/pegacorn-ssl-certs"
      volumeHostPath: "/volumes/workspace0/aether/deployment/certificates"
    - volumeName: "configfiles"
      volumeMountPath: "/var/lib/configfiles"
      volumeHostPath: "/volumes/workspace0/aether/deployment/configfiles/"
    - volumeName: "transformfiles"
      volumeMountPath: "/var/lib/subsystem"
      volumeHostPath: "/volumes/workspace0/aether/deployment/transforms/subsystem"
hapiAPIKey:
  credentialName: null
  credentialPassword: null
  credentialReferenceName: "hapi-fhir-secrets"
  credentialReferenceKey: "hapiApiKey"
javaDeploymentParameters:
  jmxMaxHeapSizeMB: "1024Mi"
  jvmMemSizeMB: null
petasosIPCMessagingEndpoint:
  name: "petasos-ipc"
  targetPortValue: 14691
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
petasosTopologyDiscoveryEndpoint:
  name: "petasos-top"
  targetPortValue: 16692
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
petasosTaskServicesEndpoint:
  name: "petasos-task"
  targetPortValue: 16691
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
petasosSubscriptionsEndpoint:
  name: "petasos-sub"
  targetPortValue: 16693
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
petasosInterceptionEndpoint:
  name: "petasos-snoop"
  targetPortValue: 16694
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
petasosMetricsEndpoint:
  name: "petasos-metric"
  targetPortValue: 16695
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
multiuseInfinispanEndpoint:
  name: "multi-infini"
  targetPortValue: 16696
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
petasosAuditServicesEndpoint:
  name: "petasos-audit"
  targetPortValue: 16698
  portType: "endpoint.ipc_messaging.jgroups_interzone_client"
  targetHostName: "0.0.0.0"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-IZR-Client"
      interfaceDefinitionVersion: "1.0.0"
edgeAnswer:
  name: "edge-answer"
  serverPort: 16270
  portType: "endpoint.restful"
  serverHostname: "0.0.0.0"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "Fast Healthcare Interoperability Resources"
      interfaceDefinitionVersion: "4.0.1"
  servicePort: 16270
  servicePortName: null
  serviceDNS: "mitaf-hips-server"
  clusterServicePortOffsetValue: 0
  contextPath: null
  server: true
  encrypted: true
interactEgressPASEventUpdate:
  name: "pas-event-out"
  portType: "endpoint.restful"
  defaultRetryCount: 3
  defaultRetryWait: 10000
  defaultTimeout: 5000
  connectedSystem:
    owningOrganizationName: "Unknown"
    solutionName: "HIPS"
    subsystemName: "HIPS"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "hips"
    externalisedServiceEndpointName: "http-server"
    targetPort1:
      targetInterfaceDefinition:
        interfaceDefinitionName: "HIPS-HTTP"
        interfaceDefinitionVersion: "vx.x"
      encryptionRequired: "true"
      targetPortValue: 22578
      targetPortDNSName: "192.168.56.101"
interactEgressORUImagingUpdate:
  name: "oru-image-out"
  portType: "endpoint.restful"
  defaultRetryCount: 3
  defaultRetryWait: 10000
  defaultTimeout: 5000
  connectedSystem:
    owningOrganizationName: "Unknown"
    solutionName: "HIPS"
    subsystemName: "HIPS"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "hips"
    externalisedServiceEndpointName: "http-server"
    targetPort1:
      targetInterfaceDefinition:
        interfaceDefinitionName: "HIPS-HTTP"
        interfaceDefinitionVersion: "vx.x"
      encryptionRequired: "true"
      targetPortValue: 22578
      targetPortDNSName: "192.168.56.101"
interactEgressORUPathologyUpdate:
  name: "oru-path-out"
  portType: "endpoint.restful"
  defaultRetryCount: 3
  defaultRetryWait: 10000
  defaultTimeout: 5000
  connectedSystem:
    owningOrganizationName: "Unknown"
    solutionName: "HIPS"
    subsystemName: "HIPS"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "hips"
    externalisedServiceEndpointName: "http-server"
    targetPort1:
      targetInterfaceDefinition:
        interfaceDefinitionName: "HIPS-HTTP"
        interfaceDefinitionVersion: "vx.x"
      encryptionRequired: "true"
      targetPortValue: 22578
      targetPortDNSName: "192.168.56.101"
