---
subsystemInstant:
  owningOrganizationName: "ACT Health"
  solutionName: "AETHER"
  solutionGroup: "au.gov.act.health.aether"
  solutionDescription: Message Ingestion, Transformation and Forwarding (MITaF) - PRBC
  subsystemName: "aether-mitaf-bloodbank"
  subsystemVersion: "1.5.0"
  externalisedServiceName: "aether-mitaf-bloodbank"
  externalisedServiceDNSName: "mitaf-bloodbank.sitea.aether.local"
  externalisedServiceEndpointName: null
  clusterServiceName: "aether-mitaf-bloodbank"
  clusterServiceDNSName: "10.123.123.2"
  processingPlantName: "AETHER.MITaF.BloodBank"
  processingPlantDNSName: "aether-mitaf-bloodbank"
  processingPlantVersion: "1.0.0-SNAPSHOT"
deploymentMode:
  deploymentConfig: "systemconfig-microk8s-site-a.yaml"
  interNetworkIPCStackConfigFile: "site-a-multi-zone-ipc-microk8s.xml"
  intraNetworkIPCStackConfigFile: "site-a-private-network-ipc.xml"
  interNetworkOAMStackConfigFile: "site-a-multi-zone-oam-microk8s.xml"
  intraNetworkOAMStackConfigFile: "site-a-private-network-oam.xml"
  kubernetes: true
  processingPlantReplicationCount: 1
  concurrent: false
  usingInternalEncryption: true
deploymentSites:
  siteCount: 1
  site1Name: "Site-A"
  site2Name: null
  site3Name: null
deploymentZone:
  securityZoneName: "private-network"
  nameSpace: "site-a"
kubeReadinessProbe:
  serverPort: 9990
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/health"
  server: true
  encrypted: false
  startupDelay: 60
kubeLivelinessProbe:
  serverPort: 9990
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/health"
  server: true
  encrypted: false
  startupDelay: 60
prometheusPort:
  serverPort: 0
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/"
  server: true
  encrypted: false
jolokiaPort:
  serverPort: 8080
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles: []
  contextPath: "/"
  server: true
  encrypted: false
subsystemImageProperties:
  repository: "localhost:32000/"
  imageName: "aether-mitaf-bloodbank"
  imageVersion: "1.0.0-SNAPSHOT"
  pullPolicy: "Always"
defaultServicePortLowerBound: 16160
loadBalancer:
  type: "LoadBalancer"
  ipAddress: "10.123.123.2"
volumeMounts:
  volumeMountName: "certificates"
  volumeMountPath: "/var/lib/pegacorn-ssl-certs"
  volumeName: "certificates"
  volumeHostPath: "/volumes/workspace0/data/"
hapiAPIKey:
  credentialName: null
  credentialPassword: null
  credentialReferenceName: "hapi-fhir-secrets"
  credentialReferenceKey: "hapiApiKey"
javaDeploymentParameters:
  jmxMaxHeapSizeMB: "1024Mi"
  jvmMemSizeMB: null
interZoneIPC:
  name: "inter-zone-ipc"
  serverPort: 14702
  portType: "endpoint.ipc_messaging.jgroups_interzone"
  serverHostname: "0.0.0.0"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-Gossip"
      interfaceDefinitionVersion: "1.0.0"
  initialHosts:
    - hostName: "aether-petasos-gossiprouter-one-site-a"
      portNumber: "17004"
    - hostName: "aether-petasos-gossiprouter-two-site-a"
      portNumber: "17006"
  server: "true"
  encrypted: "false"
intraZoneIPC:
  name: "intra-zone-ipc"
  serverPort: 14700
  portType: "endpoint.ipc_messaging.jgroups_intrazone"
  serverHostname: "0.0.0.0"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-Kube"
      interfaceDefinitionVersion: "1.0.0"
  initialHosts:
    - hostName: "localhost"
      portNumber: "14700"
  server: "true"
  encrypted: "false"
interZoneOAM:
  name: "inter-zone-oam"
  serverPort: 14703
  portType: "endpoint.ipc_messaging.jgroups_interzone"
  serverHostname: "0.0.0.0"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-Gossip"
      interfaceDefinitionVersion: "1.0.0"
  initialHosts:
    - hostName: "aether-petasos-gossiprouter-one-site-a"
      portNumber: "17005"
    - hostName: "aether-petasos-gossiprouter-two-site-a"
      portNumber: "17007"
  server: "true"
  encrypted: "false"
intraZoneOAM:
  name: "intra-zone-oam"
  serverPort: 14701
  portType: "endpoint.ipc_messaging.jgroups_intrazone"
  serverHostname: "0.0.0.0"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "JGroups-Kube"
      interfaceDefinitionVersion: "1.0.0"
  initialHosts:
    - hostName: "localhost"
      portNumber: "14700"
  server: "true"
  encrypted: "false"
edgeAnswer:
  name: "edge-answer"
  serverPort: 16260
  portType: "TCP"
  serverHostname: null
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "Fast Healthcare Interoperability Resources"
      interfaceDefinitionVersion: "4.0.1"
  servicePort: 16260
  servicePortName: null
  serviceDNS: null
  clusterServicePortOffsetValue: 0
  contextPath: null
  server: true
  encrypted: true
interactAuxIngres:
  name: "oru-aux-in"
  serverHostname: "0.0.0.0"
  serverPort: 16261
  portType: "endpoint.mllp_server"
  server: "true"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "MLLP"
      interfaceDefinitionVersion: "v2.x"
  servicePort: 16261
  serviceDNS: "aether-mitaf-bloodbank-site-a"
  connectedSystem:
    owningOrganizationName: "ACT Health"
    solutionName: "Citadel"
    subsystemName: "BloodBank"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "bloodbank-aether-integration"
    externalisedServiceEndpointName: "mllp-sender"
interactPamIngres:
  name: "oru-pam-in"
  serverHostname: "0.0.0.0"
  serverPort: 16262
  portType: "endpoint.mllp_server"
  server: "true"
  encrypted: "false"
  supportedInterfaceProfiles:
    - interfaceDefinitionName: "MLLP"
      interfaceDefinitionVersion: "v2.x"
  servicePort: 16262
  serviceDNS: "aether-mitaf-bloodbank-site-a"
  connectedSystem:
    owningOrganizationName: "ACT Health"
    solutionName: "Citadel"
    subsystemName: "BloodBank"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "bloodbank-aether-integration"
    externalisedServiceEndpointName: "mllp-sender"
interactORMBTSEgress:
  name: "gen-ormbts-out"
  portType: "endpoint.mllp_client"
  portParameters: null;
  defaultRetryCount: 3
  defaultRetryWait: 10000
  defaultTimeout: 5000
  connectedSystem:
    owningOrganizationName: "ACT Health"
    solutionName: "Citadel"
    subsystemName: "BloodBank"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "bloodbank-aether-integration"
    externalisedServiceEndpointName: "mllp-receiver"
    targetPort1:
      targetInterfaceDefinition:
        interfaceDefinitionName: "MLLP"
        interfaceDefinitionVersion: "v2.x"
      encryptionRequired: "true"
      targetPortValue: 5500
      targetPortDNSName: "192.168.56.101"
interactADTEgress:
  name: "gen-adt-out"
  portType: "endpoint.mllp_client"
  portParameters: null;
  defaultRetryCount: 3
  defaultRetryWait: 10000
  defaultTimeout: 5000
  connectedSystem:
    owningOrganizationName: "ACT Health"
    solutionName: "Citadel"
    subsystemName: "BloodBank"
    subsystemVersion: "1.5.0"
    externalisedServiceName: "bloodbank-aether-integration"
    externalisedServiceEndpointName: "mllp-receiver"
    targetPort1:
      targetInterfaceDefinition:
        interfaceDefinitionName: "MLLP"
        interfaceDefinitionVersion: "v2.x"
      encryptionRequired: "true"
      targetPortValue: 5510
      targetPortDNSName: "192.168.56.101"