---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if (.Values.dnsEntry) }} 
    # From https://docs.microsoft.com/en-us/azure/aks/internal-lb#create-an-internal-load-balancer
    service.beta.kubernetes.io/azure-load-balancer-internal: "{{ .Values.loadBalancerInternal | default true }}"
#    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsEntry }}
    # From https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/rfc2136.md
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsEntry }}
    {{- end }}    
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    app: {{ .Values.subsystemInstant.subsystemName }}
    version: {{ .Values.subsystemInstant.processingPlantVersion }}
    group: {{ .Values.subsystemInstant.solutionGroup }}
  name: {{ .Values.subsystemInstant.subsystemName }}
spec:
  ports:
    - name: {{ .Values.edgeAnswer.name }}
      port: {{ .Values.edgeAnswer.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.edgeAnswer.serverPort }}
  selector:
    app: {{ .Values.subsystemInstant.subsystemName }}
    group: {{ .Values.subsystemInstant.solutionGroup }}
  type: {{ .Values.serviceType | default "LoadBalancer" }}
  {{- if (.Values.subsystemInstant.clusterServiceDNSName) }} 
  loadBalancerIP:  {{ .Values.subsystemInstant.clusterServiceDNSName }}
  {{- end }}
